sudo: false
language: cpp

branches:
  only:
    - devel
    - travis

matrix:
  include:
    - os: linux
      compiler: clang
      env: C=clang A=-m64 B=debug
    - os: linux
      compiler: clang
      env: C=clang A=-m64
    - os: linux
      compiler: gcc
      env: C=gcc A=-m64
    - os: linux
      compiler: gcc
      env: C=gcc A=-m64 B=sanitize
    - os: linux
      compiler: gcc-5
      env: C=gcc-5 A=-m64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    - os: linux
      compiler: gcc-5
      env: C=gcc-5 A=-m32
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5-multilib
            - zlib1g-dev:i386
    - os: osx
      compiler: clang
      env: C=clang A=-m64 ALLOW_FAIL=1
      #osx_image: xcode7

install:
  - DEPS_DIR="$TRAVIS_BUILD_DIR/deps"
  - mkdir -p "$DEPS_DIR" && cd "$DEPS_DIR"
  - wget --no-check-certificate -q -O - https://download.freenas.org/distfiles/ucl-1.03.tar.gz | tar -xz
  - git clone https://github.com/upx/upx-testsuite

script:
  - bash "$TRAVIS_BUILD_DIR/.travis_build.sh"
